name: Technitium DNS Server
slug: technitium_dns
version: 1.0.3
description: Run Technitium DNS Server as a Home Assistant OS add-on.
url: https://github.com/Dion/ha-technitium
startup: services
boot: auto
init: false
arch:
  - amd64
  - aarch64
  - armv7
host_network: true
ports:
  53/tcp: 53
  53/udp: 53
  5380/tcp: 5380
ingress: true
ingress_port: 5380
panel_icon: mdi:dns
panel_title: Technitium DNS
ports_description:
  53/tcp: DNS service over TCP
  53/udp: DNS service over UDP
  5380/tcp: Technitium DNS Server web UI
map:
  - type: addon_config
    read_only: false
    path: /config
options: {}
schema: {}
